#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo -e "${GREEN}📩 Checking commit message...${NC}"

branch_name=$(git symbolic-ref --short HEAD)

if echo "$branch_name" | grep -Eq "^(dev|main|master)$"; then
  echo -e "${GREEN}✅ Branch '$branch_name' is allowed without commit message check.${NC}"
  exit 0
fi

# Checking commit message with commitlint
if ! npx --no -- commitlint --edit "$1"; then
  echo -e "${RED}❌ Commit message does not follow conventions.${NC}"
  echo -e "${GREEN}✅ Format: <type>(SHARK-<taskId>): <short description>${NC}"
  echo -e "${GREEN}   Example: feat(SHARK-334): add liquidity form${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Commit message is valid!${NC}"
